[package]
name = "mc_symbol_table"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
clap = "2.33"
mc_parser = { path = "../mc_parser" }

[dev-dependencies]
pest = "2.1.3"